### ISSUE TITLE
generic types with a wild card throw exception

### ISSUE THREAD

**Issue by h8nry** [json-iterator/java#108]
```
Caused by: com.jsoniter.spi.JsonException: unsupported type: ?, of class class sun.reflect.generics.reflectiveObjects.WildcardTypeImpl
	at com.jsoniter.spi.TypeLiteral.formatTypeWithoutSpecialCharacter(TypeLiteral.java:145)
	at com.jsoniter.spi.TypeLiteral.formatTypeWithoutSpecialCharacter(TypeLiteral.java:137)
	at com.jsoniter.spi.TypeLiteral.generateCacheKey(TypeLiteral.java:109)
	... 20 more
```

**Comment by taowen** [comment]
more info is required

**Comment by h8nry** [comment]
here is an easy way to reproduce it...

```
public class JsoniterTest {
	
	public static class TestObject<T> {
		
		private final Class<T> t;
		
		public TestObject(Class<T> t) {
			this.t = t;
		}
	}

	public static void main(String[] args) {
		Set<TestObject<?>> set = new HashSet<JsoniterTest.TestObject<?>>();
		set.add(new TestObject<String>(String.class));
		System.out.println(JsonStream.serialize(set));
	}
}

```

**Comment by taowen** [comment]
? is not supported

**Comment by toastnjamz** [comment]
I'm having the same issue when I use Apache's MultiValuedMap: https://commons.apache.org/proper/commons-collections/apidocs/org/apache/commons/collections4/MultiValuedMap.html

Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.jsoniter.spi.JsonException: failed to generate cache key for: ParameterizedTypeImpl{actualTypeArguments=[class java.lang.Object, ? extends java.util.Collection<V>], ownerType=null, rawType=java.util.Map}] with root cause

com.jsoniter.spi.JsonException: unsupported type: ? extends java.util.Collection<V>, of class class sun.reflect.generics.reflectiveObjects.WildcardTypeImpl
